import { MetaShop, MetaBazaar } from '../types';

// Full sample shops in the native MetaShop import format.
// Importing either one builds a complete shop (theme, cover/background image, logo,
// contact, and products/services) that you can then fine-tune in the editor.

const CF = 'https://d8j0ntlcm91z4.cloudfront.net/user_37LxMnMIKo1nDrfSeM1P16PUV6Y';

export const PRODUCTS_SAMPLE: MetaShop = {
  id: 'sample-products',
  slug: 'iranian-fresh-produce',
  name: 'Premium Iranian Fresh Produce',
  type: 'products',
  isActive: true,
  currency: 'USD',
  theme: {
    primary: '#2d4a1a',
    cover: '#2d4a1a',
    coverText: '#fdfbf6',
    bg: '#fdfbf6',
    heading: '#1f2a18',
    text: '#2d3a24',
  },
  collectionText: 'Iranian Fresh Produce Range',
  title: 'PREMIUM IRANIAN FRESH PRODUCE CATALOGUE',
  subtitle: 'From Iranian Orchards & Greenhouses to Global Markets via Sohar Port — 2026 Edition',
  coverImage: `${CF}/hf_20260515_160733_5dc0c535-0fb8-478b-8c7b-e456964d7213.png`,
  logo: '',
  phone: '+968 98 1030 64',
  email: 'info@tohiddayhami.com',
  website: 'www.tohiddayhami.com',
  address: 'Muscat, Sultanate of Oman | CR No. 1617064 | Cold-chain ex Sohar Port',
  footerText: 'Tohid Dayhami Business Solutions | Premium Iranian Fresh Produce Exporter | Cold-chain via Sohar, Oman',
  cartButtonText: 'Request FOB/CIF Quote',
  orderThankYouText: 'Thank you! Your fresh produce inquiry has been received. We will prepare a proforma invoice with FOB Sohar / CIF pricing within 24 hours. Keep your tracking code below.',
  searchPlaceholder: 'Search all products...',
  defaultLang: 'en',
  directoryCats: [{ fa: 'مواد غذایی', en: 'Food' }, { fa: 'صادراتی', en: 'Export' }], directorySub: { fa: 'خشکبار و میوه', en: 'Nuts & Dried Fruit' }, code: 'FRSH',
  languages: [{ code: 'en', name: 'English' }, { code: 'zh', name: '中文' }],
  i18n: { zh: { title: '高级伊朗新鲜农产品目录', subtitle: '从伊朗果园和温室经苏哈尔港销往全球 — 2026 版', collectionText: '伊朗新鲜农产品系列' } },
  productsTabLabel: 'فهرست محصولات',
  productsTabLabelEn: 'Product List',
  assignType: undefined,
  assignedPersonnelIds: [],
  extraFees: [
    { id: 'fee-ship', label: 'هزینه ارسال', labelEn: 'Shipping fee', amount: 2, required: false, defaultOn: true },
    { id: 'fee-pack', label: 'هزینه بسته‌بندی ویژه', labelEn: 'Special packaging', amount: 1, required: false, defaultOn: false },
  ],
  discounts: [
    { id: 'disc-nowruz', code: 'NOWRUZ', type: 'percent', value: 10, scope: 'all', active: true, label: 'Nowruz 10% off everything' },
    { id: 'disc-pistachio', code: 'PISTACHIO5', type: 'fixed', value: 5, scope: 'products', productIds: ['sp1'], active: true, label: '$5 off pistachios' },
  ],
  taxRate: 9,
  taxInclusive: false,
  taxLabel: 'مالیات بر ارزش افزوده',
  taxLabelEn: 'VAT',
  pages: [
    {
      id: 'pg-about', label: 'درباره ما', labelEn: 'About Us', type: 'text',
      bodyEn: 'Tohid Dayhami Business Solutions is a Muscat-based exporter of premium Iranian fresh produce, dried fruits, nuts, and specialty agricultural products. We operate strategic cold-chain logistics from Sohar Port, Sultanate of Oman — serving 30+ countries.\n\nWe source the very best from Iran’s flagship regions: Akbari pistachios from Rafsanjan, Piarom dates from Hormozgan, Sargol saffron from Qaenat, Rabab pomegranates from Neyriz, and year-round hydroponic greenhouse vegetables.\n\nEvery shipment is fully certified — Global G.A.P., HACCP, ISO 22000:2018, Halal, and Phytosanitary Certificate. Selected lines carry EU Organic certification.',
      body: 'توحید دیهمی بیزینس سولوشنز صادرکننده‌ی محصولات تازه و خشک‌بار ممتاز ایرانی مستقر در مسقط است. ما لجستیک زنجیره سرد را از بندر صحار عمان مدیریت می‌کنیم و به بیش از ۳۰ کشور خدمات می‌دهیم.\n\nبهترین‌ها را از مناطق شاخص ایران تأمین می‌کنیم: پسته اکبری رفسنجان، خرمای پیارم هرمزگان، زعفران سرگل قائنات، انار رباب نِی‌ریز و سبزیجات گلخانه‌ای تمام‌فصل.\n\nهر محموله دارای گواهی‌های Global G.A.P، HACCP، ISO 22000، حلال و بهداشت گیاهی است.',
      images: [`${CF}/hf_20260515_160741_f6b419f8-74d1-424a-bc12-4c1bd7b192ba.png`, `${CF}/hf_20260515_160750_2669ecb7-f9ab-472f-a053-aaca6be06b3d.png`],
    },
    {
      id: 'pg-certs', label: 'گواهینامه‌ها و استانداردها', labelEn: 'Certifications & Standards', type: 'cards',
      descriptionEn: 'Every shipment carries the full suite of international certifications — giving our clients market access worldwide.',
      description: 'هر محموله مجموعه کامل گواهینامه‌های بین‌المللی را دارد تا دسترسی مشتریان ما به بازارهای جهانی تضمین شود.',
      cards: [
        { id: 'cc1', name: 'Global G.A.P.', nameEn: 'Global G.A.P.', descEn: 'Good Agricultural Practices certification across all supplier farms.', desc: 'گواهی شیوه‌های خوب کشاورزی برای همه مزارع تأمین‌کننده.', image: `${CF}/hf_20260515_160847_556a5f3d-a753-4850-bbff-90f87e225963.png` },
        { id: 'cc2', name: 'HACCP', nameEn: 'HACCP Certified', descEn: 'Hazard Analysis & Critical Control Points food-safety system.', desc: 'سیستم ایمنی غذایی تحلیل خطر و نقاط کنترل بحرانی.', image: `${CF}/hf_20260515_160855_6a23e8d2-0071-4bda-9f42-fe63722b097c.png` },
        { id: 'cc3', name: 'ISO 22000:2018', nameEn: 'ISO 22000:2018', descEn: 'International food-safety management system certification.', desc: 'گواهی سیستم مدیریت ایمنی غذایی بین‌المللی.', image: `${CF}/hf_20260515_160903_e2be6f66-a062-4cfc-a88a-69e646721398.png` },
        { id: 'cc4', name: 'Phytosanitary', nameEn: 'Phytosanitary Certificate', descEn: 'Plant-health certificate issued for every export shipment.', desc: 'گواهی بهداشت گیاهی برای هر محموله صادراتی.', image: `${CF}/hf_20260515_160910_8ffc307d-99f9-4df7-bb6b-90615dfcdb7e.png` },
        { id: 'cc5', name: 'HALAL', nameEn: 'HALAL Certified', descEn: 'Compliance with Islamic dietary law across the product range.', desc: 'مطابقت با قوانین غذایی اسلامی در کل سبد محصولات.', image: `${CF}/hf_20260515_160917_c3c38086-67da-4de0-8238-2c0e06d73039.png` },
        { id: 'cc6', name: 'EU Organic', nameEn: 'EU Organic Certified', descEn: 'European Union Organic certification for select product lines.', desc: 'گواهی ارگانیک اتحادیه اروپا برای خطوط منتخب.', image: `${CF}/hf_20260515_160924_024f6c10-dafb-4f5c-853b-8d59c731fc80.png` },
      ],
    },
  ],
  products: [
    { id: 'sp1', name: 'Premium Akbari Pistachios — 1kg Vacuum Pack', sku: 'TDH-PIS-AKB-1KG', hsCode: '08025100', group: 'Iconic Iranian Specialties', subcategory: 'Nuts', description: 'Top-grade long Akbari pistachios from Rafsanjan, vacuum-packed for freshness.', i18n: { zh: { name: '高级阿克巴里开心果 — 1公斤真空装', description: '来自拉夫桑詹的顶级长形阿克巴里开心果，真空包装保鲜。' } }, images: [`${CF}/hf_20260515_160554_0e06b51a-499d-44c9-92ac-74d09dd74696.png`, `${CF}/hf_20260515_160741_f6b419f8-74d1-424a-bc12-4c1bd7b192ba.png`, `${CF}/hf_20260515_160750_2669ecb7-f9ab-472f-a053-aaca6be06b3d.png`], active: true, currency: 'USD', price: 13.5, packPrice: 13.5, unit: 'kg', pack: 1, moq: '8000', stockLabel: 'In stock', origin: { name: 'Iran' } },
    { id: 'sp2', name: 'Piarom Dates — 500g Royal Gift Box', sku: 'TDH-DAT-PRM-500', hsCode: '08041000', group: 'Iconic Iranian Specialties', subcategory: 'Dates', description: 'Semi-dry Piarom (Maryami) dates from Hormozgan in an elegant gift box.', images: [`${CF}/hf_20260515_160602_e9e83a3c-473e-4b3e-a86d-7728c6665998.png`], active: true, currency: 'USD', price: 11, packPrice: 5.5, unit: 'kg', pack: 0.5, moq: '12000', stockLabel: 'In stock' },
    { id: 'sp3', name: 'Sargol Saffron — 5g Premium Vial', sku: 'TDH-SAF-SGL-5G', hsCode: '09102010', group: 'Iconic Iranian Specialties', subcategory: 'Saffron', description: 'All-red Sargol saffron from Qaenat, coloring strength 240+.', images: [`${CF}/hf_20260515_160610_f586a550-da82-413e-8d6f-1a79e64434fb.png`], active: true, currency: 'USD', price: 2200, packPrice: 11, unit: 'kg', pack: 0.005, moq: '50', stockLabel: 'In stock' },
    { id: 'sp4', name: 'Iranian Red Apples — 10kg Export Carton', sku: 'TDH-APP-RED-10', hsCode: '08081000', group: 'Premium Fresh Fruits', subcategory: 'Pome Fruits', description: 'Crisp Damavand high-altitude red apples, export-graded and waxed.', images: [`${CF}/hf_20260515_160627_d2dc14af-3a49-473a-a8b4-221301f05428.png`], active: true, currency: 'USD', price: 0.95, packPrice: 9.5, unit: 'kg', pack: 10, moq: '100000', stockLabel: 'In stock', priceOptions: [{ id: 'o-fob', label: 'FOB', labelEn: 'FOB', price: 0.95 }, { id: 'o-cif', label: 'CIF', labelEn: 'CIF', price: 1.15 }, { id: 'o-ddp', label: 'DDP', labelEn: 'DDP', price: 1.45 }] },
    { id: 'sp5', name: 'Rabab Pomegranates — 8kg Export Carton', sku: 'TDH-POM-RAB-8', hsCode: '08109010', group: 'Premium Fresh Fruits', subcategory: 'Pome Fruits', description: 'Sweet-tart Rabab pomegranates from Neyriz, deep ruby arils.', images: [`${CF}/hf_20260515_160635_1a90f764-ce39-4a58-b31e-ea3ee4c63363.png`], active: true, currency: 'USD', price: 1.4, packPrice: 11.2, unit: 'kg', pack: 8, moq: '60000', stockLabel: 'In stock' },
    { id: 'sp6', name: 'Greenhouse Vine Tomatoes — 5kg Export Carton', sku: 'TDH-TOM-VIN-5', hsCode: '07020000', group: 'Greenhouse Vegetables', description: 'Year-round hydroponic vine tomatoes from Yazd greenhouses.', images: [`${CF}/hf_20260515_160659_b1702d1b-ce9e-489b-9fee-e288bdbea9a4.png`], active: true, currency: 'USD', price: 0.85, packPrice: 4.25, unit: 'kg', pack: 5, moq: '150000', stockLabel: 'In stock' },
    { id: 'sp7', name: 'Yellow Onions — 25kg Export Mesh Sack', sku: 'TDH-ONI-YEL-25', hsCode: '07031019', group: 'Strategic Storage Crops', description: 'Long-shelf-life yellow onions in breathable mesh sacks.', images: [`${CF}/hf_20260515_160724_1b9081bc-deac-4357-b172-714513cfe8ee.png`], active: true, currency: 'USD', price: 0.35, packPrice: 8.75, unit: 'kg', pack: 25, moq: '500000', stockLabel: 'In stock' },
  ],
};

export const SERVICES_SAMPLE: MetaShop = {
  id: 'sample-services',
  slug: 'tohid-services',
  name: 'Tohid Dayhami Services',
  type: 'services',
  isActive: true,
  currency: 'OMR',
  theme: {
    primary: '#0f766e',
    cover: '#0f172a',
    coverText: '#f8fafc',
    bg: '#ffffff',
    heading: '#0f172a',
    text: '#334155',
  },
  collectionText: 'Professional Services',
  title: 'Tohid Dayhami — Business & Mobility Services',
  subtitle: 'Consulting, market entry, design and car rental — book online and we will get back to you.',
  coverImage: `${CF}/hf_20260515_160741_f6b419f8-74d1-424a-bc12-4c1bd7b192ba.png`,
  logo: '',
  phone: '+968 98 1030 64',
  email: 'info@tohiddayhami.com',
  website: 'www.tohiddayhami.com',
  address: 'Muscat, Sultanate of Oman',
  footerText: 'Tohid Dayhami Business Solutions — Services Division',
  cartButtonText: 'Request Service',
  orderThankYouText: 'Thank you! Your service request has been received. Our team will contact you shortly. Keep your tracking code below.',
  searchPlaceholder: 'Search services...',
  defaultLang: 'fa',
  directoryCats: [{ fa: 'خدمات', en: 'Services' }, { fa: 'صادراتی', en: 'Export' }], directorySub: { fa: 'اجاره و مشاوره', en: 'Rental & Consulting' }, code: 'SRVC',
  languages: [{ code: 'fa', name: 'فارسی', rtl: true }, { code: 'en', name: 'English' }, { code: 'zh', name: '中文' }],
  i18n: { zh: { title: 'Tohid Dayhami — 商务与出行服务', subtitle: '咨询、市场进入、设计与租车 — 在线预订，我们会尽快与您联系。', collectionText: '专业服务' } },
  productsTabLabel: 'خدمات',
  productsTabLabelEn: 'Services',
  assignType: undefined,
  assignedPersonnelIds: [],
  extraFees: [
    { id: 'fee-delivery', label: 'هزینه تحویل در محل', labelEn: 'On-site delivery', amount: 3, required: false, defaultOn: false },
  ],
  discounts: [
    { id: 'disc-rent', code: 'RENT10', type: 'percent', value: 10, scope: 'categories', categories: ['Car Rental'], active: true, label: '10% off car rentals' },
  ],
  taxRate: 5,
  taxInclusive: true,
  taxLabel: 'مالیات بر ارزش افزوده',
  taxLabelEn: 'VAT',
  pages: [
    {
      id: 'pg-about', label: 'درباره ما', labelEn: 'About Us', type: 'text',
      body: 'مجموعه خدمات توحید دیهمی شامل مشاوره صادرات و ورود به بازار، طراحی برند و بسته‌بندی، و اجاره خودرو در مسقط است. تیم ما با تجربه‌ی بین‌المللی در کنار شماست.',
      bodyEn: 'Tohid Dayhami Services covers export & market-entry consulting, brand & packaging design, and car rental in Muscat. Our internationally experienced team is here for you.',
      images: [`${CF}/hf_20260515_160750_2669ecb7-f9ab-472f-a053-aaca6be06b3d.png`],
    },
  ],
  products: [
    { id: 'ss1', name: 'Export Market-Entry Consulting', sku: 'SVC-CONSULT-EXP', group: 'Consulting', description: 'One-on-one strategic consulting session for entering GCC & global markets: pricing, logistics, certifications.', images: [`${CF}/hf_20260515_160822_b37cc5a5-15ca-4401-91d4-eb896a48fc09.png`], active: true, currency: 'OMR', price: 45, unit: 'session', priceUnit: 'per session', features: [{ label: 'Duration', value: '90 minutes' }, { label: 'Format', value: 'Online / In-person' }] },
    { id: 'ss2', name: 'Brand & Packaging Design', sku: 'SVC-DESIGN-PKG', group: 'Design', description: 'Print-ready Adobe Illustrator packaging design + professional mockups. Includes 3 revisions.', images: [`${CF}/hf_20260515_160807_15f8d67c-56ed-4a12-9962-063b8be3924a.png`], active: true, currency: 'OMR', price: 120, unit: 'project', priceUnit: 'per project', features: [{ label: 'Deliverables', value: 'AI files + mockups' }, { label: 'Timeline', value: '~20 days' }, { label: 'Revisions', value: '3 included' }] },
    { id: 'ss3', name: 'Economy Car Rental', sku: 'SVC-CAR-ECO', group: 'Car Rental', subcategory: 'Economy', description: 'Compact economy car rental in Muscat. Insurance and 200km/day included.', i18n: { zh: { name: '经济型租车', description: '马斯喀特紧凑型经济租车，含保险及每日200公里。' } }, images: [`${CF}/hf_20260515_160830_d8bb0e62-ed41-4e9e-bf1e-3b086cacd6bf.png`], active: true, currency: 'OMR', price: 12, unit: 'rental', priceOptions: [{ id: 'd1', label: '۱ روز', labelEn: '1 day', price: 12 }, { id: 'd3', label: '۳ روز', labelEn: '3 days', price: 33 }, { id: 'd10', label: '۱۰ روز', labelEn: '10 days', price: 100 }], features: [{ label: 'Mileage', value: '200 km/day' }, { label: 'Insurance', value: 'Included' }, { label: 'Transmission', value: 'Automatic' }] },
    { id: 'ss4', name: 'SUV Rental', sku: 'SVC-CAR-SUV', group: 'Car Rental', subcategory: 'SUV', description: 'Full-size SUV rental, ideal for desert and family trips. Insurance and 250km/day included.', images: [`${CF}/hf_20260515_160838_8fda62d3-3580-4ab2-a3e6-354d406285bf.png`], active: true, currency: 'OMR', price: 28, unit: 'rental', priceOptions: [{ id: 'd1', label: '۱ روز', labelEn: '1 day', price: 28 }, { id: 'd3', label: '۳ روز', labelEn: '3 days', price: 78 }, { id: 'd10', label: '۱۰ روز', labelEn: '10 days', price: 240 }], features: [{ label: 'Mileage', value: '250 km/day' }, { label: 'Seats', value: '7' }, { label: 'Insurance', value: 'Included' }] },
  ],
};

// ── Real estate sample: rent / buy listings with full property metadata for AI + images ──
export const REALESTATE_SAMPLE: MetaShop & { _aiGuide?: Record<string, unknown> } = {
  _aiGuide: {
    purpose: 'این فایل نمونهٔ فروشگاه املاک MetaShop است. با دادن همین ساختار به هوش مصنوعی (همراه تصاویر)، می‌توان آگهی‌های کامل اجاره/فروش ساخت.',
    shopType: 'realestate — حتماً type را realestate بگذارید. سبد خرید و تعداد ندارد؛ مشتری «درخواست بازدید» ثبت می‌کند.',
    customerQuestions: [
      'قیمت کل / اجاره ماهانه / ودیعه چقدر است؟ → price (فروش) یا realEstate.monthlyRent + realEstate.deposit (اجاره)',
      'کجاست؟ آدرس دقیق؟ → city, district, neighborhood, fullAddress, mapUrl, nearbyPlaces[]',
      'چند متر؟ چند خواب؟ → areaSqm, landAreaSqm, bedrooms, bathrooms, floor, totalFloors',
      'سند چیست؟ قابل وام؟ → documentType, ownership, loanEligible',
      'تحویل کی؟ سکونت فعلی؟ → availableFrom, occupancyStatus',
      'مبله است؟ نوساز؟ → furnished, yearBuilt, renovatedYear, renovation',
      'پارکینگ / انباری / آسانسور؟ → parkingSpaces, parkingType, storage, elevator',
      'گرمایش / سرمایش / کف / آشپزخانه؟ → heating, cooling, flooring, kitchen',
      'برای مغازه: مجوز کسب؟ بر ملک؟ تردد؟ → commercialLicense, frontageMeters, footTraffic, powerCapacity',
      'حیوان خانگی؟ حداقل مدت اجاره؟ → petsAllowed, minLeaseMonths, leaseDuration',
      'قابل مذاکره؟ کمیسیون؟ → negotiable, commission',
      'تور مجازی / پلان؟ → virtualTourUrl, floorPlanUrl, images[] (حداقل ۳–۸ عکس: نما، پذیرایی، آشپزخانه، خواب، سرویس، پارکینگ، محله)',
      'سوالات رایج مشتری؟ → realEstate.faq[] با q/a فارسی، qEn/aEn انگلیسی، qAr/aAr عربی، یا faq[].i18n.{کد}.{q,a} برای زبان‌های دیگر',
      'ترجمهٔ مقادیر مشخصات (کاربری، شهر، امکانات…): روش ۱) فیلد فارسی + پسوند En/Ar مثل usageEn، cityAr، amenitiesEn[] — روش ۲) realEstate.i18n.{کد}.{field} — روش ۳) products[].i18n.{کد}.realEstate.{field} برای هر زبان جدید (zh، tr، …)',
      'نکات مهم برای مشتری؟ → description + realEstate.publicHighlights[]',
      'تماس مشاور؟ → realEstate.agentName, agentPhone, agentWhatsapp + shop.phone/email',
    ],
    dealTypes: { sale: 'فروش', rent: 'اجاره بلندمدت', 'rent-short': 'اجاره کوتاه‌مدت/روزانه', 'pre-sale': 'پیش‌فروش', exchange: 'معاوضه' },
    propertyTypes: { apartment: 'آپارتمان', villa: 'ویلا', penthouse: 'پنت‌هاوس', studio: 'سوئیت', shop: 'مغازه تجاری', office: 'دفتر', warehouse: 'انبار', industrial: 'صنعتی', land: 'زمین', building: 'ساختمان', hotel: 'هتل/مهمان‌پذیر' },
    requiredPerListing: ['name', 'description', 'images (۳+)', 'realEstate.dealType', 'realEstate.propertyType', 'realEstate.areaSqm', 'realEstate.city', 'realEstate.district', 'price (فقط نمایش فروش) یا monthlyRent+deposit (اجاره)', 'realEstate.faq (۵+ سوال)'],
    noCart: 'املاک کالا نیست — qty و سبد خرید ندارید. price فقط برای نمایش قیمت فروش است؛ اجاره از monthlyRent و deposit.',
    importNote: 'در پنل MetaShop: ساخت از JSON یا به‌روزرسانی از فایل — فیلد _aiGuide فقط راهنماست و ذخیره نمی‌شود.',
  },
  id: 'sample-realestate',
  slug: 'tohid-realestate',
  name: 'املاک توحید دیهمی',
  type: 'realestate',
  isActive: true,
  currency: 'IRR',
  theme: {
    primary: '#1e3a5f',
    cover: '#0f2744',
    coverText: '#f8fafc',
    bg: '#f8faf6',
    heading: '#0f172a',
    text: '#334155',
  },
  collectionText: 'خرید · اجاره · سرمایه‌گذاری',
  title: 'املاک توحید دیهمی — خرید و اجاره در تهران و شهرهای بزرگ',
  subtitle: 'آپارتمان، ویلا، مغازه تجاری، دفتر اداری و زمین — با مشخصات کامل، عکس، نقشه و پاسخ به سوالات متداول',
  coverImage: `${CF}/hf_20260515_160741_f6b419f8-74d1-424a-bc12-4c1bd7b192ba.png`,
  logo: '',
  phone: '+98 912 000 0000',
  email: 'realestate@tohiddayhami.com',
  website: 'www.tohiddayhami.com',
  address: 'تهران، خیابان ولیعصر، برج میراث — واحد مشاوره املاک',
  footerText: 'املاک توحید دیهمی | مشاوره خرید، فروش و اجاره | تمامی آگهی‌ها دارای بازدید حضوری و مجازی',
  cartButtonText: 'درخواست بازدید و مشاوره',
  orderThankYouText: 'درخواست بازدید شما ثبت شد. مشاور املاک ظرف ۲۴ ساعت با شما تماس می‌گیرد. کد رهگیری را نگه دارید.',
  searchPlaceholder: 'جستجو: منطقه، متراژ، نوع ملک...',
  defaultLang: 'fa',
  directoryCats: [{ fa: 'املاک', en: 'Real Estate' }, { fa: 'اجاره و فروش', en: 'Rent & Sale' }],
  directorySub: { fa: 'مسکونی و تجاری', en: 'Residential & Commercial' },
  code: 'RLST',
  languages: [{ code: 'fa', name: 'فارسی', rtl: true }, { code: 'ar', name: 'العربية', rtl: true }, { code: 'en', name: 'English' }],
  productsTabLabel: 'املاک',
  productsTabLabelEn: 'Properties',
  assignType: undefined,
  assignedPersonnelIds: [],
  extraFees: [],
  discounts: [],
  taxRate: 0,
  taxInclusive: true,
  pages: [
    {
      id: 'pg-about', label: 'درباره ما', labelEn: 'About', type: 'text',
      body: 'بخش املاک توحید دیهمی با تیم مشاوران مجرب در زمینه خرید، فروش، اجاره و سرمایه‌گذاری ملکی فعالیت می‌کند. تمام آگهی‌ها با بازدید حضوری، عکس حرفه‌ای و پاسخ شفاف به سوالات حقوقی و فنی ارائه می‌شوند.',
      bodyEn: 'Tohid Dayhami Real Estate offers expert advisory for buying, selling, renting and property investment. Every listing includes on-site visits, professional photos and clear answers to legal and technical questions.',
      images: [`${CF}/hf_20260515_160750_2669ecb7-f9ab-472f-a053-aaca6be06b3d.png`],
    },
    {
      id: 'pg-process', label: 'مراحل معامله', labelEn: 'How it works', type: 'cards',
      description: 'از بازدید تا تحویل کلید — شفاف و قابل پیگیری',
      descriptionEn: 'From viewing to handover — transparent and trackable',
      cards: [
        { id: 'c1', name: 'بازدید', nameEn: 'Viewing', desc: 'هماهنگی بازدید حضوری یا تور مجازی در کمتر از ۲۴ ساعت.', descEn: 'Schedule an in-person or virtual tour within 24 hours.', image: `${CF}/hf_20260515_160822_b37cc5a5-15ca-4401-91d4-eb896a48fc09.png` },
        { id: 'c2', name: 'بررسی حقوقی', nameEn: 'Legal review', desc: 'استعلام سند، بدهی شهرداری و وضعیت رهن/تعهدات.', descEn: 'Title deed check, municipal debts and encumbrances.', image: `${CF}/hf_20260515_160807_15f8d67c-56ed-4a12-9962-063b8be3924a.png` },
        { id: 'c3', name: 'قرارداد و تحویل', nameEn: 'Contract', desc: 'تنظیم مبایعه‌نامه یا اجاره‌نامه رسمی و تحویل کلید.', descEn: 'Official sale or lease contract and key handover.', image: `${CF}/hf_20260515_160830_d8bb0e62-ed41-4e9e-bf1e-3b086cacd6bf.png` },
      ],
    },
  ],
  products: [
    {
      id: 're-apartment-sale',
      name: 'آپارتمان ۱۲۰ متری ۳ خواب — سعادت‌آباد',
      sku: 'RL-TH-SAD-120',
      group: 'فروش مسکونی',
      subcategory: 'آپارتمان',
      description: 'آپارتمان نوساز ۱۲۰ متر در سعادت‌آباد با نمای باز، آشپزخانه اپن، کف سرامیک و پارکینگ اختصاصی. مناسب خانواده؛ نزدیک مترو و مراکز خرید.',
      images: [
        `${CF}/hf_20260515_160554_0e06b51a-499d-44c9-92ac-74d09dd74696.png`,
        `${CF}/hf_20260515_160741_f6b419f8-74d1-424a-bc12-4c1bd7b192ba.png`,
        `${CF}/hf_20260515_160750_2669ecb7-f9ab-472f-a053-aaca6be06b3d.png`,
        `${CF}/hf_20260515_160602_e9e83a3c-473e-4b3e-a86d-7728c6665998.png`,
      ],
      active: true, currency: 'IRR', price: 18500000000, featured: true,
      realEstate: {
        dealType: 'sale', propertyType: 'apartment', usage: 'مسکونی',
        areaSqm: 120, bedrooms: 3, bathrooms: 2, floor: 5, totalFloors: 8, yearBuilt: 1401,
        documentType: 'سند تک‌برگ', ownership: 'شخصی', occupancyStatus: 'خالی — آماده سکونت',
        furnished: 'بدون مبلمان', parkingSpaces: 1, parkingType: 'اختصاصی مسقف',
        storage: true, balcony: true, balconySqm: 8, elevator: true,
        heating: 'شوفاژ مرکزی', cooling: 'اسپلیت', flooring: 'سرامیک', kitchen: 'اپن — کابینت های‌گلاس',
        pricePerSqm: 154166667, maintenanceFee: 2500000, negotiable: true, commission: '۲٪ طرفین',
        city: 'تهران', province: 'تهران', district: 'سعادت‌آباد', neighborhood: 'میدان کاج',
        fullAddress: 'تهران، سعادت‌آباد، خیابان سرو غربی، پلاک ۴۲، واحد ۵۰۲',
        mapUrl: 'https://maps.google.com/?q=Saadat+Abad+Tehran',
        nearbyPlaces: ['مترو سعادت‌آباد — ۸ دقیقه پیاده', 'مرکز خرید مگامال — ۵ دقیقه', 'مدرسه بین‌المللی — ۱۰ دقیقه'],
        amenities: ['لابی شیک', 'نگهبانی ۲۴ ساعته', 'دوربین مداربسته', 'سالن ورزشی', 'استخر'],
        buildingFeatures: ['نمای سنگ', 'سیستم اطفاء', 'آسانسور برقی'],
        security: ['نگهبانی', 'درب رقیق', 'آیفون تصویری'],
        loanEligible: true, availableFrom: 'فوری',
        virtualTourUrl: 'https://example.com/tour/saadat-apt',
        agentName: 'آقای رضایی', agentPhone: '+989120000001', agentWhatsapp: '+989120000001',
        publicHighlights: ['نورگیر عالی جنوبی', 'بدون پرونده معوق شهرداری', 'قابل تبدیل به وام مسکن'],
        faq: [
          { q: 'قیمت نهایی چقدر است؟', qEn: 'What is the final price?', a: '۱۸ میلیارد و ۵۰۰ میلیون تومان — قابل مذاکره تا ۳٪.', aEn: '18.5 billion Toman — up to 3% negotiable.' },
          { q: 'سند مشکل حقوقی دارد؟', qEn: 'Any legal issues with the title?', a: 'خیر؛ سند تک‌برگ، بدون رهن و وکالت.', aEn: 'No; freehold single-sheet deed, no mortgage or power of attorney.' },
          { q: 'شارژ ماهانه چقدر است؟', qEn: 'Monthly maintenance fee?', a: 'حدود ۲٫۵ میلیون تومان شامل نگهبانی و آسانسور.', aEn: 'About 2.5M Toman including security and elevator.' },
          { q: 'وام مسکن می‌گیرد؟', qEn: 'Eligible for housing loan?', a: 'بله؛ مدارک کامل برای بانک‌های منتخب آماده است.', aEn: 'Yes; documents ready for partner banks.' },
          { q: 'پارکینگ و انباری دارد؟', qEn: 'Parking and storage?', a: 'یک پارکینگ مسقف + انباری ۴ متری.', aEn: 'One covered parking + 4 m² storage.' },
        ],
      },
    },
    {
      id: 're-apartment-rent',
      name: 'اجاره آپارتمان ۸۵ متری ۲ خواب — اصفهان جلفا',
      sku: 'RL-ISF-RENT-85',
      group: 'اجاره مسکونی',
      subcategory: 'آپارتمان',
      description: 'آپارتمان مبله کامل در محله تاریخی جلفا، مناسب خانواده کوچک یا زوج؛ نزدیک زاینده‌رود و کافه‌ها.',
      images: [`${CF}/hf_20260515_160838_8fda62d3-3580-4ab2-a3e6-354d406285bf.png`, `${CF}/hf_20260515_160807_15f8d67c-56ed-4a12-9962-063b8be3924a.png`],
      active: true, currency: 'IRR', price: 0,
      realEstate: {
        dealType: 'rent', propertyType: 'apartment', usage: 'مسکونی',
        areaSqm: 85, bedrooms: 2, bathrooms: 1, floor: 2, totalFloors: 4, yearBuilt: 1395,
        documentType: 'سند مادر', occupancyStatus: 'خالی از اول ماه آینده',
        furnished: 'مبله کامل', parkingSpaces: 0, elevator: false,
        monthlyRent: 45000000, rentCurrency: 'IRR', deposit: 900000000, rentPeriod: 'ماهانه',
        minLeaseMonths: 12, utilitiesIncluded: ['آب'],
        heating: 'بخاری گازی', cooling: 'کولر آبی', kitchen: 'جزیره‌ای — لوازم کامل',
        negotiable: true, commission: 'معادل یک ماه اجاره',
        city: 'اصفهان', province: 'اصفهان', district: 'جلفا', neighborhood: 'خیابان حکیم',
        fullAddress: 'اصفهان، جلفا، کوچه گلستان، پلاک ۱۸، واحد ۴',
        mapUrl: 'https://maps.google.com/?q=Jolfa+Isfahan',
        nearbyPlaces: ['پل خواجو — ۱۲ دقیقه', 'ایستگاه اتوبوس — ۳ دقیقه'],
        petsAllowed: 'خیر', availableFrom: '۱۴۰۵/۰۴/۰۱', leaseDuration: 'حداقل ۱ سال',
        agentName: 'خانم احمدی', agentPhone: '+989120000002',
        publicHighlights: ['مبله لوکس', 'محله آرام گردشگری', 'قبوض برق و گاز با مستأجر'],
        faq: [
          { q: 'ودیعه و اجاره چقدر است؟', qEn: 'Deposit and rent?', a: 'ودیعه ۹۰۰ میلیون + اجاره ماهانه ۴۵ میلیون تومان.', aEn: '900M deposit + 45M monthly rent.' },
          { q: 'قبوض با کیست؟', qEn: 'Who pays utilities?', a: 'آب شامل اجاره؛ برق و گاز با مستأجر.', aEn: 'Water included; electricity and gas by tenant.' },
          { q: 'حیوان خانگی مجاز است؟', qEn: 'Pets allowed?', a: 'خیر، طبق قوانین ساختمان.', aEn: 'No, per building rules.' },
          { q: 'حداقل مدت قرارداد؟', qEn: 'Minimum lease?', a: '۱۲ ماه با چک ۳ ماهه.', aEn: '12 months with quarterly cheques.' },
        ],
      },
    },
    {
      id: 're-shop-commercial',
      name: 'مغازه ۴۵ متری تجاری — شیراز زند',
      sku: 'RL-SHZ-SHOP-45',
      group: 'تجاری',
      subcategory: 'مغازه',
      description: 'مغازه در پاساژ پرتردد خیابان زند با ویترین ۸ متری، مناسب پوشاک، آرایشی یا خدمات.',
      images: [`${CF}/hf_20260515_160822_b37cc5a5-15ca-4401-91d4-eb896a48fc09.png`, `${CF}/hf_20260515_160830_d8bb0e62-ed41-4e9e-bf1e-3b086cacd6bf.png`],
      active: true, currency: 'IRR', price: 12000000000,
      realEstate: {
        dealType: 'sale', propertyType: 'shop', usage: 'تجاری',
        areaSqm: 45, floor: 0, yearBuilt: 1388, renovatedYear: 1402,
        documentType: 'سند تجاری', commercialLicense: 'پروانه کسب فعال — قابل انتقال',
        frontageMeters: 8, ceilingHeight: 3.5, powerCapacity: 'سه‌فاز ۳۲ آمپر',
        footTraffic: 'بسیار پرتردد — خیابان زند', currentTenant: 'خالی — آماده تحویل',
        parkingSpaces: 0, elevator: false, negotiable: true,
        pricePerSqm: 266666667, city: 'شیراز', province: 'فارس', district: 'زند',
        fullAddress: 'شیراز، خیابان زند، پاساژ نگین، واحد ۱۲',
        mapUrl: 'https://maps.google.com/?q=Zand+Shiraz',
        nearbyPlaces: ['بازار وکیل — ۵ دقیقه', 'پارکینگ عمومی — ۲ دقیقه'],
        amenities: ['ویترین شیشه‌ای', 'سرویس بهداشتی', 'انبارک پشت مغازه'],
        agentPhone: '+989120000003',
        faq: [
          { q: 'مجوز کسب دارد؟', qEn: 'Business license?', a: 'بله؛ پروانه کسب فعال و قابل انتقال به خریدار.', aEn: 'Yes; active license transferable to buyer.' },
          { q: 'بر ملک چند متر است؟', qEn: 'Shop frontage?', a: '۸ متر ویترین رو به خیابان اصلی.', aEn: '8 m frontage on main street.' },
          { q: 'برق چند فاز است؟', qEn: 'Power supply?', a: 'سه‌فاز ۳۲ آمپر — مناسب یخچال صنعتی و کولر.', aEn: '3-phase 32A — suitable for commercial cooling.' },
        ],
      },
    },
    {
      id: 're-land',
      name: 'زمین ۵۰۰ متری مسکونی — کرج گوهردشت',
      sku: 'RL-KRJ-LAND-500',
      group: 'زمین و کلنگی',
      subcategory: 'زمین',
      description: 'زمین مسکونی در بلوار اصلی گوهردشت با سند تک‌برگ، مناسب ساخت ویلا یا سرمایه‌گذاری.',
      images: [`${CF}/hf_20260515_160910_8ffc307d-99f9-4df7-bb6b-90615dfcdb7e.png`],
      active: true, currency: 'IRR', price: 25000000000,
      realEstate: {
        dealType: 'sale', propertyType: 'land', usage: 'مسکونی',
        landAreaSqm: 500, areaSqm: 500, documentType: 'سند تک‌برگ — پایان کار ندارد',
        facing: 'شمالی', negotiable: true, loanEligible: false,
        city: 'کرج', province: 'البرز', district: 'گوهردشت',
        fullAddress: 'کرج، گوهردشت، بلوار موذن، پلاک ۲۵۰',
        mapUrl: 'https://maps.google.com/?q=Gohardasht+Karaj',
        nearbyPlaces: ['مترو گوهردشت — ۱۵ دقیقه', 'مراکز خرید — ۵ دقیقه'],
        publicHighlights: ['دو بر — بر ۱۵ و ۱۲ متر', 'داخل بافت مسکونی', 'بدون بدهی عوارض'],
        faq: [
          { q: 'قیمت هر متر چقدر است؟', qEn: 'Price per m²?', a: '۵۰ میلیون تومان هر متر — جمع ۲۵ میلیارد.', aEn: '50M per m² — total 25 billion.' },
          { q: 'پایان کار دارد؟', qEn: 'Building permit?', a: 'خیر؛ زمین خام مسکونی با سند تک‌برگ.', aEn: 'No; raw residential land with freehold deed.' },
        ],
      },
    },
    {
      id: 're-villa',
      name: 'ویلای ۳۵۰ متری باغ — شمال تهران لواسان',
      sku: 'RL-TH-VILA-350',
      group: 'فروش ویلایی',
      subcategory: 'ویلا',
      description: 'ویلای دوبلکس در باغ ۱۰۰۰ متری با استخر، آلاچیق و نمای کوه — مناسب سکونت دائم یا دوم.',
      images: [`${CF}/hf_20260515_160917_c3c38086-67da-4de0-8238-2c0e06d73039.png`, `${CF}/hf_20260515_160924_024f6c10-dafb-4f5c-853b-8d59c731fc80.png`, `${CF}/hf_20260515_160903_e2be6f66-a062-4cfc-a88a-69e646721398.png`],
      active: true, currency: 'IRR', price: 45000000000, featured: true,
      realEstate: {
        dealType: 'sale', propertyType: 'villa', usage: 'مسکونی ویلایی',
        areaSqm: 350, landAreaSqm: 1000, bedrooms: 4, bathrooms: 3, yearBuilt: 1398,
        documentType: 'سند تک‌برگ', view: 'کوه و باغ', facing: 'جنوبی',
        parkingSpaces: 3, parkingType: 'حیاط سرپوشیده', storage: true, balcony: true,
        heating: 'موتورخانه مرکزی', cooling: 'داکت اسپلیت', flooring: 'سنگ و پارکت',
        kitchen: 'جزیره‌ای — کابینت چوب',
        pricePerSqm: 128571429, negotiable: true,
        city: 'تهران', district: 'لواسان', neighborhood: 'باغستان',
        fullAddress: 'لواسان، جاده باغستان، انتهای کوچه بنفشه',
        mapUrl: 'https://maps.google.com/?q=Lavasan+Tehran',
        nearbyPlaces: ['جاده لواسان — ۵ دقیقه', 'سوپرمارکت — ۳ دقیقه'],
        amenities: ['استخر', 'آلاچیق', 'باربیکیو', 'سیستم آبیاری', 'دوربین مداربسته'],
        security: ['دیوار دور باغ', 'درب ریموت', 'نگهبان شبانه'],
        loanEligible: true, virtualTourUrl: 'https://example.com/tour/lavasan-villa',
        agentName: 'آقای کریمی', agentPhone: '+989120000004',
        publicHighlights: ['آب لوله‌کشی و برق سه‌فاز', 'سند آماده انتقال', 'قابل معاوضه با آپارتمان تهران'],
        faq: [
          { q: 'آب و برق چگونه است؟', qEn: 'Utilities?', a: 'آب لوله‌کشی شهری + برق سه‌فاز؛ گاز کپسول.', aEn: 'Municipal water + 3-phase power; LPG gas.' },
          { q: 'استخر سالم است؟', qEn: 'Pool condition?', a: 'بله؛ بازسازی ۱۴۰۳ با سیستم تصفیه جدید.', aEn: 'Yes; renovated 2024 with new filtration.' },
          { q: 'معاوضه می‌دهید؟', qEn: 'Open to exchange?', a: 'بله؛ معاوضه با آپارتمان بالای ۱۵۰ متر در تهران.', aEn: 'Yes; exchange for 150+ m² apartment in Tehran.' },
        ],
      },
    },
  ],
};

// Sample bazaar: a curated, multi-level directory (Country → City → Product group) of shops.
export const BAZAAR_SAMPLE: MetaBazaar = {
  id: 'sample-bazaar',
  slug: 'tohid-bazaar',
  name: 'Tohid Bazaar',
  isActive: true,
  defaultLang: 'en',
  title: { fa: 'بازارچه توحید دیهمی', en: 'Tohid Dayhami Bazaar' },
  subtitle: { fa: 'فروشگاه‌ها بر اساس کشور، شهر و گروه کالایی', en: 'Shops by country, city and product group' },
  coverImage: '',
  logo: '',
  theme: { primary: '#2d4a1a', cover: '#1f2a18' },
  // Optional names for each nesting level (depth 0,1,2,...). Leave empty to hide level labels.
  levelLabels: [{ fa: 'کشور', en: 'Country' }, { fa: 'شهر', en: 'City' }, { fa: 'گروه کالایی', en: 'Product Group' }],
  tree: [
    {
      id: 'n-iran', label: { fa: 'ایران', en: 'Iran' },
      children: [
        {
          id: 'n-tehran', label: { fa: 'تهران', en: 'Tehran' },
          children: [
            { id: 'n-food', label: { fa: 'مواد غذایی', en: 'Food' }, shopSlugs: ['iranian-fresh-produce'] },
            { id: 'n-services', label: { fa: 'خدمات', en: 'Services' }, shopSlugs: ['tohid-services'] },
          ],
        },
        {
          id: 'n-mashhad', label: { fa: 'مشهد', en: 'Mashhad' },
          children: [
            { id: 'n-saffron', label: { fa: 'زعفران', en: 'Saffron' }, shopSlugs: [] },
          ],
        },
      ],
    },
    {
      id: 'n-oman', label: { fa: 'عمان', en: 'Oman' },
      children: [
        { id: 'n-muscat', label: { fa: 'مسقط', en: 'Muscat' }, shopSlugs: ['tohid-services'] },
      ],
    },
  ],
  expo: {
    enabled: true,
    defaultLang: 'en',
    languages: [
      { code: 'en', name: 'English' },
      { code: 'fa', name: 'فارسی', rtl: true },
      { code: 'ar', name: 'العربية', rtl: true },
    ],
    visualStyle: 'exhibition',
    title: {
      en: 'Tohid Dayhami Virtual Bazaar',
      fa: 'بازارچه مجازی توحید دیهمی',
      ar: 'سوق توحيد ديهامي الافتراضي',
    },
    subtitle: {
      en: 'Explore shops in English, Persian or Arabic',
      fa: 'فروشگاه‌ها را به فارسی، انگلیسی یا عربی ببینید',
      ar: 'استكشف المتاجر بالعربية أو الفارسية أو الإنجليزية',
    },
    entranceEnabled: true,
    width: 30,
    depth: 30,
    height: 9,
    spawn: { x: 0, y: 0, z: 8 },
    booths: [],
  },
};

export const downloadSample = (kind: 'products' | 'services' | 'realestate' | 'bazaar' | 'expo') => {
  const data = kind === 'products' ? PRODUCTS_SAMPLE : kind === 'services' ? SERVICES_SAMPLE : kind === 'realestate' ? REALESTATE_SAMPLE : kind === 'expo'
    ? { _instructions: { fa: 'نمونه expo چندزبانه — در JSON بازارچه قرار دهید یا Update from JSON', en: 'Multilingual expo sample — merge into bazaar JSON' }, expo: BAZAAR_SAMPLE.expo }
    : BAZAAR_SAMPLE;
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = kind === 'bazaar' ? 'metashop-sample-bazaar.json' : kind === 'expo' ? 'metashop-sample-expo.json' : `metashop-sample-${kind}.json`;
  a.click();
  URL.revokeObjectURL(url);
};
